<Project>
  <PropertyGroup>
    <Version>2.0.0-rc.1</Version>
    <SpyBrowserPackageVersion Condition="'$(SpyBrowserPackageVersion)' == ''">0.2.0-beta.2.1</SpyBrowserPackageVersion>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(MSBuildThisFileDirectory)artifacts/spybrowser-feed</RestoreAdditionalProjectSources>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
