<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
    <ProjectReference Include="..\..\src\RpaFlow.Editor\RpaFlow.Editor.csproj" />
    <ProjectReference Include="..\..\src\RpaFlow.Contracts\RpaFlow.Contracts.csproj" />
    <ProjectReference Include="..\..\src\RpaFlow.Packages\RpaFlow.Packages.csproj" />
    <ProjectReference Include="..\..\src\RpaFlow.Playwright\RpaFlow.Playwright.csproj" />
    <ProjectReference Include="..\..\src\RpaFlow.Runtime\RpaFlow.Runtime.csproj" />
  </ItemGroup>
</Project>
