using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

var repositoryRoot = FindRepositoryRoot(AppContext.BaseDirectory);
var schemaPaths = new[]
{
    Path.Combine(repositoryRoot, "schemas", "flow-v2.schema.json"),
    Path.Combine(repositoryRoot, "schemas", "locators-v1.schema.json"),
    Path.Combine(repositoryRoot, "schemas", "rpa-policy-v1.schema.json")
};
var schemas = schemaPaths.Select(path => new SchemaDocument(
    path,
    JsonNode.Parse(File.ReadAllText(path, Encoding.UTF8))!.AsObject())).ToArray();
var hash = ComputeHash(schemaPaths);
var builder = new StringBuilder();
builder.AppendLine("// <auto-generated>");
builder.AppendLine("// Gerado de schemas/*.schema.json. Não edite manualmente.");
builder.AppendLine($"// schemas-sha256: {hash}");
builder.AppendLine("// </auto-generated>");
builder.AppendLine();

var emitted = new HashSet<string>(StringComparer.Ordinal);
foreach (var schema in schemas)
{
    if (schema.Root["$defs"] is JsonObject definitions)
    {
        foreach (var (name, node) in definitions)
        {
            var typeName = ToPascalCase(name);
            if (!emitted.Add(typeName))
            {
                throw new InvalidOperationException(
                    $"O nome TypeScript '{typeName}' foi gerado mais de uma vez.");
            }

            EmitNamedType(builder, typeName, node!);
        }
    }

    var rootName = ToPascalCase(
        schema.Root["title"]?.GetValue<string>()
        ?? Path.GetFileNameWithoutExtension(schema.Path));
    if (!emitted.Add(rootName))
    {
        throw new InvalidOperationException(
            $"O nome TypeScript raiz '{rootName}' foi gerado mais de uma vez.");
    }

    EmitNamedType(builder, rootName, schema.Root);
}

var outputDirectory = Path.Combine(repositoryRoot, "schemas", "generated");
Directory.CreateDirectory(outputDirectory);
var outputPath = Path.Combine(outputDirectory, "contracts.ts");
var contents = builder.ToString().TrimEnd('\r', '\n').ReplaceLineEndings("\n") + "\n";
File.WriteAllText(outputPath, contents, new UTF8Encoding(false, true));
Console.WriteLine(Path.GetRelativePath(repositoryRoot, outputPath));

static void EmitNamedType(StringBuilder builder, string name, JsonNode node)
{
    if (node is JsonObject definition && IsObjectSchema(definition))
    {
        builder.Append("export interface ").Append(name).AppendLine(" {");
        EmitProperties(builder, definition, indentation: "  ");
        builder.AppendLine("}");
        builder.AppendLine();
        return;
    }

    builder.Append("export type ").Append(name).Append(" = ")
        .Append(TypeFor(node)).AppendLine(";");
    builder.AppendLine();
}

static void EmitProperties(StringBuilder builder, JsonObject schema, string indentation)
{
    var required = schema["required"] is JsonArray requiredArray
        ? requiredArray.Select(item => item!.GetValue<string>())
            .ToHashSet(StringComparer.Ordinal)
        : [];
    if (schema["properties"] is JsonObject properties)
    {
        foreach (var (propertyName, propertySchema) in properties)
        {
            builder.Append(indentation)
                .Append(FormatPropertyName(propertyName));
            if (!required.Contains(propertyName))
            {
                builder.Append('?');
            }

            builder.Append(": ").Append(TypeFor(propertySchema!)).AppendLine(";");
        }
    }

    if (schema["additionalProperties"] is JsonObject additionalProperties)
    {
        builder.Append(indentation)
            .Append("[key: string]: ")
            .Append(TypeFor(additionalProperties))
            .AppendLine(";");
    }
}

static string TypeFor(JsonNode node)
{
    if (node is JsonValue value && value.TryGetValue<bool>(out var boolean))
    {
        return boolean ? "unknown" : "never";
    }

    if (node is not JsonObject schema)
    {
        return "unknown";
    }

    if (schema["$ref"] is JsonValue referenceValue)
    {
        var reference = referenceValue.GetValue<string>();
        return ToPascalCase(reference[(reference.LastIndexOf('/') + 1)..]);
    }

    if (schema["const"] is JsonNode constant)
    {
        return Literal(constant);
    }

    if (schema["enum"] is JsonArray enumeration)
    {
        return string.Join(" | ", enumeration.Select(item => Literal(item!)));
    }

    var type = schema["type"]?.GetValue<string>();
    switch (type)
    {
        case "string":
            return "string";
        case "number":
        case "integer":
            return "number";
        case "boolean":
            return "boolean";
        case "null":
            return "null";
        case "array":
            return $"Array<{TypeFor(schema["items"] ?? JsonValue.Create(true)!)}>";
        case "object":
            return ObjectType(schema);
    }

    if (schema["oneOf"] is JsonArray oneOf)
    {
        return string.Join(" | ", oneOf.Select(item => TypeFor(item!)));
    }

    if (schema["allOf"] is JsonArray allOf)
    {
        return string.Join(" & ", allOf.Select(item => TypeFor(item!)));
    }

    return "unknown";
}

static string ObjectType(JsonObject schema)
{
    if (schema["properties"] is not JsonObject properties)
    {
        return schema["additionalProperties"] is JsonObject additional
            ? $"Record<string, {TypeFor(additional)}>"
            : "Record<string, unknown>";
    }

    var required = schema["required"] is JsonArray requiredArray
        ? requiredArray.Select(item => item!.GetValue<string>())
            .ToHashSet(StringComparer.Ordinal)
        : [];
    var parts = properties.Select(property =>
        $"{FormatPropertyName(property.Key)}" +
        (required.Contains(property.Key) ? string.Empty : "?") +
        $": {TypeFor(property.Value!)}");
    return "{ " + string.Join("; ", parts) + " }";
}

static bool IsObjectSchema(JsonObject schema) =>
    schema["type"]?.GetValue<string>() == "object" &&
    schema["properties"] is JsonObject;

static string Literal(JsonNode node) =>
    node is JsonValue value && value.TryGetValue<string>(out var text)
        ? System.Text.Json.JsonSerializer.Serialize(text)
        : node.ToJsonString();

static string FormatPropertyName(string value) =>
    Regex.IsMatch(value, "^[A-Za-z_$][A-Za-z0-9_$]*$", RegexOptions.CultureInvariant)
        ? value
        : System.Text.Json.JsonSerializer.Serialize(value);

static string ToPascalCase(string value)
{
    var parts = Regex.Split(value, "[^A-Za-z0-9]+", RegexOptions.CultureInvariant)
        .Where(part => part.Length > 0)
        .ToArray();
    if (parts.Length == 0)
    {
        throw new InvalidOperationException($"Não foi possível gerar nome para '{value}'.");
    }

    return string.Concat(parts.Select(part =>
        char.ToUpperInvariant(part[0]) + part[1..]));
}

static string ComputeHash(IEnumerable<string> paths)
{
    using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
    foreach (var path in paths.OrderBy(path => path, StringComparer.Ordinal))
    {
        var name = Path.GetFileName(path);
        hash.AppendData(Encoding.UTF8.GetBytes(name));
        hash.AppendData([0]);
        hash.AppendData(File.ReadAllBytes(path));
        hash.AppendData([0]);
    }

    return Convert.ToHexString(hash.GetHashAndReset());
}

static string FindRepositoryRoot(string start)
{
    var directory = new DirectoryInfo(Path.GetFullPath(start));
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "RpaBlockly.slnx")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new DirectoryNotFoundException("A raiz do repositório não foi encontrada.");
}

file sealed record SchemaDocument(string Path, JsonObject Root);
